name: zulip_workflow

on:
  schedule:
    - cron: '*/5 * * * *'    
    
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test-env

    steps:      
      - uses: actions/checkout@v4

      - name: Make the scripts executable
        run: chmod +x my-script.sh curl-test.sh

      - name: Run a custom script
        run: ./my-script.sh

      - name: Run custom message script
        env: 
          ZULIP_ORGANIZATION_NAME: ${{ vars.ZULIP_ORGANIZATION_NAME }}
          MESSAGE_RECEIVER_USER_ID: ${{ secrets.MESSAGE_RECEIVER_USER_ID}}
          USER_API_KEY: ${{ secrets.USER_API_KEY }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
        run: ./curl-test.sh

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
